// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS5SBp3ne6g5rxi87F8kTi-TknPF-Wkac',
    appId: '1:384152045500:web:d8838a6ceec5a5d3e4cdb9',
    messagingSenderId: '384152045500',
    projectId: 'baymax-2591a',
    authDomain: 'baymax-2591a.firebaseapp.com',
    storageBucket: 'baymax-2591a.firebasestorage.app',
    measurementId: 'G-LEMR6DMRLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLytiEN0vUGmqonzX9juzsWZV6a5WWjEE',
    appId: '1:384152045500:android:ef991bec4db76feee4cdb9',
    messagingSenderId: '384152045500',
    projectId: 'baymax-2591a',
    storageBucket: 'baymax-2591a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS5SBp3ne6g5rxi87F8kTi-TknPF-Wkac',
    appId: '1:384152045500:web:d87582d739b90d4ae4cdb9',
    messagingSenderId: '384152045500',
    projectId: 'baymax-2591a',
    authDomain: 'baymax-2591a.firebaseapp.com',
    storageBucket: 'baymax-2591a.firebasestorage.app',
    measurementId: 'G-TTMH159VJH',
  );
}
